#! /bin/sh
xrdb ~/.Xresources&
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh &
dunst&
sxhkd &
nitrogen --restore&
flashfocus &
restart-emax &
udiskie &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1&
picom &
pavucontrol &

bspc monitor DisplayPort-0 -d  "" "" "" "" "" "" "" "" "" ""
# bspc monitor DisplayPort-0 -d  "1" "2" "3" "4" "5" "6" "7" "8" "9" "10"

# bspc config ignore_ewmh_fullscreen all
bspc config border_width          0
bspc config window_gap            20
bspc config presel_feedback_color \#51474F
bspc config border_radius         15
bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol desktop='^7' state=floating follow=off
bspc rule -a Zathura desktop='^3' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a mpv desktop='^4' state=pseudo_tiled follow=on
# bspc rule -a Alacritty state=pseudo_tiled
bspc rule -a libreoffice-writer desktop='^3' state=floating follow=on
bspc rule -a libreoffice desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
