#! /bin/sh

sxhkd &
xrandr --output HDMI1 --mode 1920x1080 --primary
xrandr --output eDP1 --off
feh --bg-scale ~/Pictures/wallpapers/background.jpg &
compton &
flashfocus &
restart-emax &
~/.config/polybar/launch.sh
touchpad.sh &
udiskie &
light -N 5 &

bspc monitor HDMI1 -d  "" "" "" "" "" "" "" "" "" ""
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

# bspc config ignore_ewmh_fullscreen all
bspc config border_width         0
bspc config window_gap           5
bspc config presel_feedback_color \#51474F
bspc config border_radius        6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura desktop='^3' state=floating follow=on
bspc rule -a libreoffice-writer desktop='^3' state=floating follow=on
bspc rule -a libreoffice desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
