#! /bin/sh
autorandr --load desktop
nitrogen --restore
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
dropbox start&
~/.config/polybar/launch.sh &
dunst&
sxhkd &
nightmode --recover&
flashfocus &
restart-emax &
udiskie &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1&
picom &
pavucontrol &

# for java programs
export _JAVA_AWT_WM_NONREPARENTING=1

# bspc monitor DisplayPort-0 -d  "" "" "" "" "" "" "" "" "" ""
# bspc monitor DisplayPort-0 -d  "" "" "" "" "" "" "" "" "" ""
# bspc monitor DisplayPort-0 -d  "" "" "" "" "" "" "" "" "" ""
bspc monitor eDP-1 -d  "" "" "" "" "" "" "" "" "" ""
bspc monitor DisplayPort-0 -d  "" "" "" "" "" "" "" "" "" ""
bspc monitor HDMI-A-0 -d  "" "" "" "" "" "" "" "" "" ""
# bspc monitor DisplayPort-0 -d  "" "" "" "" "" "" "" "" "" ""
# bspc monitor DisplayPort-0 -d  '' '' '' '' '' '' '' '' '' ''
# bspc monitor DisplayPort-0 -d  "1" "2" "3" "4" "5" "6" "7" "8" "9" "10"

gap=20

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding -10
bspc config left_padding -5
bspc config right_padding -5
bspc config bottom_padding -10

# bspc config initial_polarity first_child

bspc config automatic_scheme alternate
bspc config directional_focus_tightness low
bspc config border_width          0
bspc config presel_feedback_color \#000000
bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol desktop='^7' state=floating follow=off
bspc rule -a Logseq desktop='^5' state=floating follow=off
# bspc rule -a Logseq desktop='^5' state=pseudo_tile follow=on
bspc rule -a Emacs state=pseudo_tiled
# bspc rule -a St state=pseudo_tiled
bspc rule -a Zathura state=pseudo_tiled
bspc rule -a Vivado state=floating
bspc rule -a St state=pseudo_tiled
# bspc rule -a Alacritty state=pseudo_tiled
# bspc rule -a Firefox state=pseudo_tiled

bspc desktop -f \^15
st -e cava &
st -e cmus &
sleep 0.4
bspc desktop -f \^5
emacs --execute '(progn (org-journal-new-entry 1) (set-frame-width (selected-frame) 150))'&
